package modelo;
// Generated 19/05/2016 10:06:57 PM by Hibernate Tools 4.3.1



/**
 * Alergias generated by hbm2java
 */
public class Alergias  implements java.io.Serializable {


     private int idAlergias;
     private Estudiante estudiante;
     private String descripcion;
     private String medicacion;

    public Alergias() {
    }

	
    public Alergias(int idAlergias, Estudiante estudiante) {
        this.idAlergias = idAlergias;
        this.estudiante = estudiante;
    }
    public Alergias(int idAlergias, Estudiante estudiante, String descripcion, String medicacion) {
       this.idAlergias = idAlergias;
       this.estudiante = estudiante;
       this.descripcion = descripcion;
       this.medicacion = medicacion;
    }
   
    public int getIdAlergias() {
        return this.idAlergias;
    }
    
    public void setIdAlergias(int idAlergias) {
        this.idAlergias = idAlergias;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getMedicacion() {
        return this.medicacion;
    }
    
    public void setMedicacion(String medicacion) {
        this.medicacion = medicacion;
    }




}


