package modelo;
// Generated 24/05/2016 11:12:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo  implements java.io.Serializable {


     private Integer idciclo;
     private Date anio;
     private Set<CicloHasGrado> cicloHasGrados = new HashSet<CicloHasGrado>(0);
     private Set<Notas> notases = new HashSet<Notas>(0);

    public Ciclo() {
    }

	
    public Ciclo(Date anio) {
        this.anio = anio;
    }
    public Ciclo(Date anio, Set<CicloHasGrado> cicloHasGrados, Set<Notas> notases) {
       this.anio = anio;
       this.cicloHasGrados = cicloHasGrados;
       this.notases = notases;
    }
   
    public Integer getIdciclo() {
        return this.idciclo;
    }
    
    public void setIdciclo(Integer idciclo) {
        this.idciclo = idciclo;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }
    public Set<CicloHasGrado> getCicloHasGrados() {
        return this.cicloHasGrados;
    }
    
    public void setCicloHasGrados(Set<CicloHasGrado> cicloHasGrados) {
        this.cicloHasGrados = cicloHasGrados;
    }
    public Set<Notas> getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set<Notas> notases) {
        this.notases = notases;
    }




}


