package modelo;
// Generated 19/05/2016 10:06:57 PM by Hibernate Tools 4.3.1



/**
 * CicloHasGrado generated by hbm2java
 */
public class CicloHasGrado  implements java.io.Serializable {


     private CicloHasGradoId id;
     private AreaCurricular areaCurricular;
     private Ciclo ciclo;
     private Grado grado;
     private Notas notas;
     private Seccion seccion;
     private int estudianteIdestudiante;

    public CicloHasGrado() {
    }

    public CicloHasGrado(CicloHasGradoId id, AreaCurricular areaCurricular, Ciclo ciclo, Grado grado, Notas notas, Seccion seccion, int estudianteIdestudiante) {
       this.id = id;
       this.areaCurricular = areaCurricular;
       this.ciclo = ciclo;
       this.grado = grado;
       this.notas = notas;
       this.seccion = seccion;
       this.estudianteIdestudiante = estudianteIdestudiante;
    }
   
    public CicloHasGradoId getId() {
        return this.id;
    }
    
    public void setId(CicloHasGradoId id) {
        this.id = id;
    }
    public AreaCurricular getAreaCurricular() {
        return this.areaCurricular;
    }
    
    public void setAreaCurricular(AreaCurricular areaCurricular) {
        this.areaCurricular = areaCurricular;
    }
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Notas getNotas() {
        return this.notas;
    }
    
    public void setNotas(Notas notas) {
        this.notas = notas;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public int getEstudianteIdestudiante() {
        return this.estudianteIdestudiante;
    }
    
    public void setEstudianteIdestudiante(int estudianteIdestudiante) {
        this.estudianteIdestudiante = estudianteIdestudiante;
    }




}


