package modelo;
// Generated 24/05/2016 11:12:06 PM by Hibernate Tools 4.3.1



/**
 * CicloHasGradoId generated by hbm2java
 */
public class CicloHasGradoId  implements java.io.Serializable {


     private int cicloIdciclo;
     private int gradoIdgrado;

    public CicloHasGradoId() {
    }

    public CicloHasGradoId(int cicloIdciclo, int gradoIdgrado) {
       this.cicloIdciclo = cicloIdciclo;
       this.gradoIdgrado = gradoIdgrado;
    }
   
    public int getCicloIdciclo() {
        return this.cicloIdciclo;
    }
    
    public void setCicloIdciclo(int cicloIdciclo) {
        this.cicloIdciclo = cicloIdciclo;
    }
    public int getGradoIdgrado() {
        return this.gradoIdgrado;
    }
    
    public void setGradoIdgrado(int gradoIdgrado) {
        this.gradoIdgrado = gradoIdgrado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CicloHasGradoId) ) return false;
		 CicloHasGradoId castOther = ( CicloHasGradoId ) other; 
         
		 return (this.getCicloIdciclo()==castOther.getCicloIdciclo())
 && (this.getGradoIdgrado()==castOther.getGradoIdgrado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCicloIdciclo();
         result = 37 * result + this.getGradoIdgrado();
         return result;
   }   


}


