package modelo;
// Generated 24/05/2016 11:12:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private Persona persona;
     private Puesto puesto;
     private String telefonoempleado;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Titulo> titulos = new HashSet<Titulo>(0);
     private Set<DatoProfesion> datoProfesions = new HashSet<DatoProfesion>(0);
     private Set<InfoDocente> infoDocentes = new HashSet<InfoDocente>(0);

    public Empleado() {
    }

	
    public Empleado(Persona persona, Puesto puesto, String telefonoempleado) {
        this.persona = persona;
        this.puesto = puesto;
        this.telefonoempleado = telefonoempleado;
    }
    public Empleado(Persona persona, Puesto puesto, String telefonoempleado, Set<Usuario> usuarios, Set<Titulo> titulos, Set<DatoProfesion> datoProfesions, Set<InfoDocente> infoDocentes) {
       this.persona = persona;
       this.puesto = puesto;
       this.telefonoempleado = telefonoempleado;
       this.usuarios = usuarios;
       this.titulos = titulos;
       this.datoProfesions = datoProfesions;
       this.infoDocentes = infoDocentes;
    }
   
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public String getTelefonoempleado() {
        return this.telefonoempleado;
    }
    
    public void setTelefonoempleado(String telefonoempleado) {
        this.telefonoempleado = telefonoempleado;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Titulo> getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set<Titulo> titulos) {
        this.titulos = titulos;
    }
    public Set<DatoProfesion> getDatoProfesions() {
        return this.datoProfesions;
    }
    
    public void setDatoProfesions(Set<DatoProfesion> datoProfesions) {
        this.datoProfesions = datoProfesions;
    }
    public Set<InfoDocente> getInfoDocentes() {
        return this.infoDocentes;
    }
    
    public void setInfoDocentes(Set<InfoDocente> infoDocentes) {
        this.infoDocentes = infoDocentes;
    }




}


