package modelo;
// Generated 19/05/2016 10:06:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private DatoProfesion datoProfesion;
     private Persona persona;
     private Titulo titulo;
     private String puesto;
     private Set<InfoDocente> infoDocentes = new HashSet<InfoDocente>(0);

    public Empleado() {
    }

	
    public Empleado(DatoProfesion datoProfesion, Persona persona, Titulo titulo, String puesto) {
        this.datoProfesion = datoProfesion;
        this.persona = persona;
        this.titulo = titulo;
        this.puesto = puesto;
    }
    public Empleado(DatoProfesion datoProfesion, Persona persona, Titulo titulo, String puesto, Set<InfoDocente> infoDocentes) {
       this.datoProfesion = datoProfesion;
       this.persona = persona;
       this.titulo = titulo;
       this.puesto = puesto;
       this.infoDocentes = infoDocentes;
    }
   
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }
    public DatoProfesion getDatoProfesion() {
        return this.datoProfesion;
    }
    
    public void setDatoProfesion(DatoProfesion datoProfesion) {
        this.datoProfesion = datoProfesion;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Titulo getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(Titulo titulo) {
        this.titulo = titulo;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Set<InfoDocente> getInfoDocentes() {
        return this.infoDocentes;
    }
    
    public void setInfoDocentes(Set<InfoDocente> infoDocentes) {
        this.infoDocentes = infoDocentes;
    }




}


