package modelo;
// Generated 24/05/2016 11:12:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private Integer idgrado;
     private String nombreGrado;
     private Set<CicloHasGrado> cicloHasGrados = new HashSet<CicloHasGrado>(0);
     private Set<GradoHasSeccion> gradoHasSeccions = new HashSet<GradoHasSeccion>(0);

    public Grado() {
    }

	
    public Grado(String nombreGrado) {
        this.nombreGrado = nombreGrado;
    }
    public Grado(String nombreGrado, Set<CicloHasGrado> cicloHasGrados, Set<GradoHasSeccion> gradoHasSeccions) {
       this.nombreGrado = nombreGrado;
       this.cicloHasGrados = cicloHasGrados;
       this.gradoHasSeccions = gradoHasSeccions;
    }
   
    public Integer getIdgrado() {
        return this.idgrado;
    }
    
    public void setIdgrado(Integer idgrado) {
        this.idgrado = idgrado;
    }
    public String getNombreGrado() {
        return this.nombreGrado;
    }
    
    public void setNombreGrado(String nombreGrado) {
        this.nombreGrado = nombreGrado;
    }
    public Set<CicloHasGrado> getCicloHasGrados() {
        return this.cicloHasGrados;
    }
    
    public void setCicloHasGrados(Set<CicloHasGrado> cicloHasGrados) {
        this.cicloHasGrados = cicloHasGrados;
    }
    public Set<GradoHasSeccion> getGradoHasSeccions() {
        return this.gradoHasSeccions;
    }
    
    public void setGradoHasSeccions(Set<GradoHasSeccion> gradoHasSeccions) {
        this.gradoHasSeccions = gradoHasSeccions;
    }




}


