package modelo;
// Generated 19/05/2016 10:06:57 PM by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Integer idhistorial;
     private Estudiante estudiante;
     private Notas notas;
     private String resultado;

    public Historial() {
    }

	
    public Historial(Estudiante estudiante, Notas notas) {
        this.estudiante = estudiante;
        this.notas = notas;
    }
    public Historial(Estudiante estudiante, Notas notas, String resultado) {
       this.estudiante = estudiante;
       this.notas = notas;
       this.resultado = resultado;
    }
   
    public Integer getIdhistorial() {
        return this.idhistorial;
    }
    
    public void setIdhistorial(Integer idhistorial) {
        this.idhistorial = idhistorial;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Notas getNotas() {
        return this.notas;
    }
    
    public void setNotas(Notas notas) {
        this.notas = notas;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


