package modelo;
// Generated 24/05/2016 11:12:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InfoDocente generated by hbm2java
 */
public class InfoDocente  implements java.io.Serializable {


     private String ceduladocente;
     private Empleado empleado;
     private Date fechaemision;
     private String claseescalafonaria;
     private Date fechaascenso;

    public InfoDocente() {
    }

	
    public InfoDocente(String ceduladocente, Empleado empleado) {
        this.ceduladocente = ceduladocente;
        this.empleado = empleado;
    }
    public InfoDocente(String ceduladocente, Empleado empleado, Date fechaemision, String claseescalafonaria, Date fechaascenso) {
       this.ceduladocente = ceduladocente;
       this.empleado = empleado;
       this.fechaemision = fechaemision;
       this.claseescalafonaria = claseescalafonaria;
       this.fechaascenso = fechaascenso;
    }
   
    public String getCeduladocente() {
        return this.ceduladocente;
    }
    
    public void setCeduladocente(String ceduladocente) {
        this.ceduladocente = ceduladocente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }
    public String getClaseescalafonaria() {
        return this.claseescalafonaria;
    }
    
    public void setClaseescalafonaria(String claseescalafonaria) {
        this.claseescalafonaria = claseescalafonaria;
    }
    public Date getFechaascenso() {
        return this.fechaascenso;
    }
    
    public void setFechaascenso(Date fechaascenso) {
        this.fechaascenso = fechaascenso;
    }




}


