package modelo;
// Generated 24/05/2016 11:12:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto  implements java.io.Serializable {


     private Integer idpuesto;
     private String cargo;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Puesto() {
    }

	
    public Puesto(String cargo) {
        this.cargo = cargo;
    }
    public Puesto(String cargo, Set<Empleado> empleados) {
       this.cargo = cargo;
       this.empleados = empleados;
    }
   
    public Integer getIdpuesto() {
        return this.idpuesto;
    }
    
    public void setIdpuesto(Integer idpuesto) {
        this.idpuesto = idpuesto;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


