package modelo;
// Generated 19/05/2016 10:06:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Titulo generated by hbm2java
 */
public class Titulo  implements java.io.Serializable {


     private int registrotitulo;
     private Date aniograduacion;
     private String profesion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Titulo() {
    }

	
    public Titulo(int registrotitulo, Date aniograduacion, String profesion) {
        this.registrotitulo = registrotitulo;
        this.aniograduacion = aniograduacion;
        this.profesion = profesion;
    }
    public Titulo(int registrotitulo, Date aniograduacion, String profesion, Set<Empleado> empleados) {
       this.registrotitulo = registrotitulo;
       this.aniograduacion = aniograduacion;
       this.profesion = profesion;
       this.empleados = empleados;
    }
   
    public int getRegistrotitulo() {
        return this.registrotitulo;
    }
    
    public void setRegistrotitulo(int registrotitulo) {
        this.registrotitulo = registrotitulo;
    }
    public Date getAniograduacion() {
        return this.aniograduacion;
    }
    
    public void setAniograduacion(Date aniograduacion) {
        this.aniograduacion = aniograduacion;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


