package modelo;
// Generated 24/05/2016 11:12:06 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idtable1;
     private Empleado empleado;
     private Rol rol;
     private String nombreUser;
     private String password;

    public Usuario() {
    }

	
    public Usuario(Empleado empleado, Rol rol) {
        this.empleado = empleado;
        this.rol = rol;
    }
    public Usuario(Empleado empleado, Rol rol, String nombreUser, String password) {
       this.empleado = empleado;
       this.rol = rol;
       this.nombreUser = nombreUser;
       this.password = password;
    }
   
    public Integer getIdtable1() {
        return this.idtable1;
    }
    
    public void setIdtable1(Integer idtable1) {
        this.idtable1 = idtable1;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombreUser() {
        return this.nombreUser;
    }
    
    public void setNombreUser(String nombreUser) {
        this.nombreUser = nombreUser;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


