package modelo;
// Generated 19/05/2016 10:06:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GradoHasSeccion generated by hbm2java
 */
public class GradoHasSeccion  implements java.io.Serializable {


     private GradoHasSeccionId id;
     private AreaCurricular areaCurricular;
     private Grado grado;
     private NivelEducativo nivelEducativo;
     private Seccion seccion;
     private Set<Notas> notases = new HashSet<Notas>(0);

    public GradoHasSeccion() {
    }

	
    public GradoHasSeccion(GradoHasSeccionId id, AreaCurricular areaCurricular, Grado grado, NivelEducativo nivelEducativo, Seccion seccion) {
        this.id = id;
        this.areaCurricular = areaCurricular;
        this.grado = grado;
        this.nivelEducativo = nivelEducativo;
        this.seccion = seccion;
    }
    public GradoHasSeccion(GradoHasSeccionId id, AreaCurricular areaCurricular, Grado grado, NivelEducativo nivelEducativo, Seccion seccion, Set<Notas> notases) {
       this.id = id;
       this.areaCurricular = areaCurricular;
       this.grado = grado;
       this.nivelEducativo = nivelEducativo;
       this.seccion = seccion;
       this.notases = notases;
    }
   
    public GradoHasSeccionId getId() {
        return this.id;
    }
    
    public void setId(GradoHasSeccionId id) {
        this.id = id;
    }
    public AreaCurricular getAreaCurricular() {
        return this.areaCurricular;
    }
    
    public void setAreaCurricular(AreaCurricular areaCurricular) {
        this.areaCurricular = areaCurricular;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public NivelEducativo getNivelEducativo() {
        return this.nivelEducativo;
    }
    
    public void setNivelEducativo(NivelEducativo nivelEducativo) {
        this.nivelEducativo = nivelEducativo;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public Set<Notas> getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set<Notas> notases) {
        this.notases = notases;
    }




}


