package modelo;
// Generated 19/05/2016 10:06:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private Integer idbnota;
     private Ciclo ciclo;
     private Estudiante estudiante;
     private GradoHasSeccion gradoHasSeccion;
     private int nota;
     private String bimestre;
     private Set<CicloHasGrado> cicloHasGrados = new HashSet<CicloHasGrado>(0);
     private Set<Historial> historials = new HashSet<Historial>(0);

    public Notas() {
    }

	
    public Notas(Ciclo ciclo, Estudiante estudiante, GradoHasSeccion gradoHasSeccion, int nota, String bimestre) {
        this.ciclo = ciclo;
        this.estudiante = estudiante;
        this.gradoHasSeccion = gradoHasSeccion;
        this.nota = nota;
        this.bimestre = bimestre;
    }
    public Notas(Ciclo ciclo, Estudiante estudiante, GradoHasSeccion gradoHasSeccion, int nota, String bimestre, Set<CicloHasGrado> cicloHasGrados, Set<Historial> historials) {
       this.ciclo = ciclo;
       this.estudiante = estudiante;
       this.gradoHasSeccion = gradoHasSeccion;
       this.nota = nota;
       this.bimestre = bimestre;
       this.cicloHasGrados = cicloHasGrados;
       this.historials = historials;
    }
   
    public Integer getIdbnota() {
        return this.idbnota;
    }
    
    public void setIdbnota(Integer idbnota) {
        this.idbnota = idbnota;
    }
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public GradoHasSeccion getGradoHasSeccion() {
        return this.gradoHasSeccion;
    }
    
    public void setGradoHasSeccion(GradoHasSeccion gradoHasSeccion) {
        this.gradoHasSeccion = gradoHasSeccion;
    }
    public int getNota() {
        return this.nota;
    }
    
    public void setNota(int nota) {
        this.nota = nota;
    }
    public String getBimestre() {
        return this.bimestre;
    }
    
    public void setBimestre(String bimestre) {
        this.bimestre = bimestre;
    }
    public Set<CicloHasGrado> getCicloHasGrados() {
        return this.cicloHasGrados;
    }
    
    public void setCicloHasGrados(Set<CicloHasGrado> cicloHasGrados) {
        this.cicloHasGrados = cicloHasGrados;
    }
    public Set<Historial> getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set<Historial> historials) {
        this.historials = historials;
    }




}


