package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private Integer idestudiante;
     private int cui;
     private String nombreEstudiante;
     private String apellidosEstudiante;
     private Date fechaNacimiento;
     private String lugarNacimiento;
     private int edad;
     private String estudiantecol;
     private Set<CicloHasGrado> cicloHasGrados = new HashSet<CicloHasGrado>(0);
     private Set<Encargado> encargados = new HashSet<Encargado>(0);
     private Set<Historial> historials = new HashSet<Historial>(0);

    public Estudiante() {
    }

	
    public Estudiante(int cui, String nombreEstudiante, String apellidosEstudiante, Date fechaNacimiento, String lugarNacimiento, int edad, String estudiantecol) {
        this.cui = cui;
        this.nombreEstudiante = nombreEstudiante;
        this.apellidosEstudiante = apellidosEstudiante;
        this.fechaNacimiento = fechaNacimiento;
        this.lugarNacimiento = lugarNacimiento;
        this.edad = edad;
        this.estudiantecol = estudiantecol;
    }
    public Estudiante(int cui, String nombreEstudiante, String apellidosEstudiante, Date fechaNacimiento, String lugarNacimiento, int edad, String estudiantecol, Set<CicloHasGrado> cicloHasGrados, Set<Encargado> encargados, Set<Historial> historials) {
       this.cui = cui;
       this.nombreEstudiante = nombreEstudiante;
       this.apellidosEstudiante = apellidosEstudiante;
       this.fechaNacimiento = fechaNacimiento;
       this.lugarNacimiento = lugarNacimiento;
       this.edad = edad;
       this.estudiantecol = estudiantecol;
       this.cicloHasGrados = cicloHasGrados;
       this.encargados = encargados;
       this.historials = historials;
    }
   
    public Integer getIdestudiante() {
        return this.idestudiante;
    }
    
    public void setIdestudiante(Integer idestudiante) {
        this.idestudiante = idestudiante;
    }
    public int getCui() {
        return this.cui;
    }
    
    public void setCui(int cui) {
        this.cui = cui;
    }
    public String getNombreEstudiante() {
        return this.nombreEstudiante;
    }
    
    public void setNombreEstudiante(String nombreEstudiante) {
        this.nombreEstudiante = nombreEstudiante;
    }
    public String getApellidosEstudiante() {
        return this.apellidosEstudiante;
    }
    
    public void setApellidosEstudiante(String apellidosEstudiante) {
        this.apellidosEstudiante = apellidosEstudiante;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getLugarNacimiento() {
        return this.lugarNacimiento;
    }
    
    public void setLugarNacimiento(String lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getEstudiantecol() {
        return this.estudiantecol;
    }
    
    public void setEstudiantecol(String estudiantecol) {
        this.estudiantecol = estudiantecol;
    }
    public Set<CicloHasGrado> getCicloHasGrados() {
        return this.cicloHasGrados;
    }
    
    public void setCicloHasGrados(Set<CicloHasGrado> cicloHasGrados) {
        this.cicloHasGrados = cicloHasGrados;
    }
    public Set<Encargado> getEncargados() {
        return this.encargados;
    }
    
    public void setEncargados(Set<Encargado> encargados) {
        this.encargados = encargados;
    }
    public Set<Historial> getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set<Historial> historials) {
        this.historials = historials;
    }




}


