package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Integer idhistorial;
     private Ciclo ciclo;
     private Estudiante estudiante;
     private Grado grado;
     private Promedio promedio;
     private Puesto puesto;
     private String resultado;

    public Historial() {
    }

	
    public Historial(Ciclo ciclo, Estudiante estudiante, Grado grado, Promedio promedio, Puesto puesto) {
        this.ciclo = ciclo;
        this.estudiante = estudiante;
        this.grado = grado;
        this.promedio = promedio;
        this.puesto = puesto;
    }
    public Historial(Ciclo ciclo, Estudiante estudiante, Grado grado, Promedio promedio, Puesto puesto, String resultado) {
       this.ciclo = ciclo;
       this.estudiante = estudiante;
       this.grado = grado;
       this.promedio = promedio;
       this.puesto = puesto;
       this.resultado = resultado;
    }
   
    public Integer getIdhistorial() {
        return this.idhistorial;
    }
    
    public void setIdhistorial(Integer idhistorial) {
        this.idhistorial = idhistorial;
    }
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Promedio getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(Promedio promedio) {
        this.promedio = promedio;
    }
    public Puesto getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Puesto puesto) {
        this.puesto = puesto;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


