package modelo;
// Generated 25/04/2016 07:48:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String dpi;
     private String nombre;
     private String apellidos;
     private String residencia;
     private String edad;
     private Date fechaNacimiento;
     private String email;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Tefono> tefonos = new HashSet<Tefono>(0);

    public Persona() {
    }

	
    public Persona(String dpi, String nombre, String apellidos, String residencia) {
        this.dpi = dpi;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.residencia = residencia;
    }
    public Persona(String dpi, String nombre, String apellidos, String residencia, String edad, Date fechaNacimiento, String email, Set<Usuario> usuarios, Set<Tefono> tefonos) {
       this.dpi = dpi;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.residencia = residencia;
       this.edad = edad;
       this.fechaNacimiento = fechaNacimiento;
       this.email = email;
       this.usuarios = usuarios;
       this.tefonos = tefonos;
    }
   
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Tefono> getTefonos() {
        return this.tefonos;
    }
    
    public void setTefonos(Set<Tefono> tefonos) {
        this.tefonos = tefonos;
    }




}


