package modelo;
// Generated 25/04/2016 07:48:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesiones generated by hbm2java
 */
public class Profesiones  implements java.io.Serializable {


     private Integer idprofesiones;
     private String profesionNombre;
     private Set<Titulo> titulos = new HashSet<Titulo>(0);

    public Profesiones() {
    }

    public Profesiones(String profesionNombre, Set<Titulo> titulos) {
       this.profesionNombre = profesionNombre;
       this.titulos = titulos;
    }
   
    public Integer getIdprofesiones() {
        return this.idprofesiones;
    }
    
    public void setIdprofesiones(Integer idprofesiones) {
        this.idprofesiones = idprofesiones;
    }
    public String getProfesionNombre() {
        return this.profesionNombre;
    }
    
    public void setProfesionNombre(String profesionNombre) {
        this.profesionNombre = profesionNombre;
    }
    public Set<Titulo> getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set<Titulo> titulos) {
        this.titulos = titulos;
    }




}


