package modelo;
// Generated 25/04/2016 07:48:26 AM by Hibernate Tools 4.3.1



/**
 * Tefono generated by hbm2java
 */
public class Tefono  implements java.io.Serializable {


     private int idTefono;
     private Persona persona;
     private Tipotelefono tipotelefono;
     private String numeroTell;

    public Tefono() {
    }

	
    public Tefono(int idTefono, Persona persona, Tipotelefono tipotelefono) {
        this.idTefono = idTefono;
        this.persona = persona;
        this.tipotelefono = tipotelefono;
    }
    public Tefono(int idTefono, Persona persona, Tipotelefono tipotelefono, String numeroTell) {
       this.idTefono = idTefono;
       this.persona = persona;
       this.tipotelefono = tipotelefono;
       this.numeroTell = numeroTell;
    }
   
    public int getIdTefono() {
        return this.idTefono;
    }
    
    public void setIdTefono(int idTefono) {
        this.idTefono = idTefono;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Tipotelefono getTipotelefono() {
        return this.tipotelefono;
    }
    
    public void setTipotelefono(Tipotelefono tipotelefono) {
        this.tipotelefono = tipotelefono;
    }
    public String getNumeroTell() {
        return this.numeroTell;
    }
    
    public void setNumeroTell(String numeroTell) {
        this.numeroTell = numeroTell;
    }




}


