package modelo;
// Generated 25/04/2016 07:48:26 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipotelefono generated by hbm2java
 */
public class Tipotelefono  implements java.io.Serializable {


     private int idtable1;
     private String telefono;
     private Set<Tefono> tefonos = new HashSet<Tefono>(0);

    public Tipotelefono() {
    }

	
    public Tipotelefono(int idtable1) {
        this.idtable1 = idtable1;
    }
    public Tipotelefono(int idtable1, String telefono, Set<Tefono> tefonos) {
       this.idtable1 = idtable1;
       this.telefono = telefono;
       this.tefonos = tefonos;
    }
   
    public int getIdtable1() {
        return this.idtable1;
    }
    
    public void setIdtable1(int idtable1) {
        this.idtable1 = idtable1;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Tefono> getTefonos() {
        return this.tefonos;
    }
    
    public void setTefonos(Set<Tefono> tefonos) {
        this.tefonos = tefonos;
    }




}


