package modelo;
// Generated 25/04/2016 07:48:26 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Titulo generated by hbm2java
 */
public class Titulo  implements java.io.Serializable {


     private int registroTitulo;
     private Profesiones profesiones;
     private Date anioGraduacion;

    public Titulo() {
    }

    public Titulo(int registroTitulo, Profesiones profesiones, Date anioGraduacion) {
       this.registroTitulo = registroTitulo;
       this.profesiones = profesiones;
       this.anioGraduacion = anioGraduacion;
    }
   
    public int getRegistroTitulo() {
        return this.registroTitulo;
    }
    
    public void setRegistroTitulo(int registroTitulo) {
        this.registroTitulo = registroTitulo;
    }
    public Profesiones getProfesiones() {
        return this.profesiones;
    }
    
    public void setProfesiones(Profesiones profesiones) {
        this.profesiones = profesiones;
    }
    public Date getAnioGraduacion() {
        return this.anioGraduacion;
    }
    
    public void setAnioGraduacion(Date anioGraduacion) {
        this.anioGraduacion = anioGraduacion;
    }




}


