package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AreaCurricular generated by hbm2java
 */
public class AreaCurricular  implements java.io.Serializable {


     private Integer idareaCurricular;
     private String nombreArea;
     private Set<Grado> grados = new HashSet<Grado>(0);
     private Set<CicloHasGrado> cicloHasGrados = new HashSet<CicloHasGrado>(0);

    public AreaCurricular() {
    }

	
    public AreaCurricular(String nombreArea) {
        this.nombreArea = nombreArea;
    }
    public AreaCurricular(String nombreArea, Set<Grado> grados, Set<CicloHasGrado> cicloHasGrados) {
       this.nombreArea = nombreArea;
       this.grados = grados;
       this.cicloHasGrados = cicloHasGrados;
    }
   
    public Integer getIdareaCurricular() {
        return this.idareaCurricular;
    }
    
    public void setIdareaCurricular(Integer idareaCurricular) {
        this.idareaCurricular = idareaCurricular;
    }
    public String getNombreArea() {
        return this.nombreArea;
    }
    
    public void setNombreArea(String nombreArea) {
        this.nombreArea = nombreArea;
    }
    public Set<Grado> getGrados() {
        return this.grados;
    }
    
    public void setGrados(Set<Grado> grados) {
        this.grados = grados;
    }
    public Set<CicloHasGrado> getCicloHasGrados() {
        return this.cicloHasGrados;
    }
    
    public void setCicloHasGrados(Set<CicloHasGrado> cicloHasGrados) {
        this.cicloHasGrados = cicloHasGrados;
    }




}


