package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1



/**
 * CicloHasGrado generated by hbm2java
 */
public class CicloHasGrado  implements java.io.Serializable {


     private CicloHasGradoId id;
     private AreaCurricular areaCurricular;
     private Ciclo ciclo;
     private Estudiante estudiante;
     private Grado grado;
     private Notas notas;
     private Seccion seccion;

    public CicloHasGrado() {
    }

    public CicloHasGrado(CicloHasGradoId id, AreaCurricular areaCurricular, Ciclo ciclo, Estudiante estudiante, Grado grado, Notas notas, Seccion seccion) {
       this.id = id;
       this.areaCurricular = areaCurricular;
       this.ciclo = ciclo;
       this.estudiante = estudiante;
       this.grado = grado;
       this.notas = notas;
       this.seccion = seccion;
    }
   
    public CicloHasGradoId getId() {
        return this.id;
    }
    
    public void setId(CicloHasGradoId id) {
        this.id = id;
    }
    public AreaCurricular getAreaCurricular() {
        return this.areaCurricular;
    }
    
    public void setAreaCurricular(AreaCurricular areaCurricular) {
        this.areaCurricular = areaCurricular;
    }
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Notas getNotas() {
        return this.notas;
    }
    
    public void setNotas(Notas notas) {
        this.notas = notas;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }




}


