package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatoProfesion generated by hbm2java
 */
@Entity
@Table(name="dato_profesion"
    ,catalog="sigie"
)
public class DatoProfesion  implements java.io.Serializable {


     private int idProfesion;
     private Personal personal;
     private Integer afiliacionIgss;
     private Date inicioLaboral;

    public DatoProfesion() {
    }

	
    public DatoProfesion(int idProfesion, Personal personal, Date inicioLaboral) {
        this.idProfesion = idProfesion;
        this.personal = personal;
        this.inicioLaboral = inicioLaboral;
    }
    public DatoProfesion(int idProfesion, Personal personal, Integer afiliacionIgss, Date inicioLaboral) {
       this.idProfesion = idProfesion;
       this.personal = personal;
       this.afiliacionIgss = afiliacionIgss;
       this.inicioLaboral = inicioLaboral;
    }
   
     @Id 

    
    @Column(name="idProfesion", unique=true, nullable=false)
    public int getIdProfesion() {
        return this.idProfesion;
    }
    
    public void setIdProfesion(int idProfesion) {
        this.idProfesion = idProfesion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Personal_DPI", nullable=false)
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }

    
    @Column(name="Afiliacion_IGSS")
    public Integer getAfiliacionIgss() {
        return this.afiliacionIgss;
    }
    
    public void setAfiliacionIgss(Integer afiliacionIgss) {
        this.afiliacionIgss = afiliacionIgss;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Inicio_laboral", nullable=false, length=10)
    public Date getInicioLaboral() {
        return this.inicioLaboral;
    }
    
    public void setInicioLaboral(Date inicioLaboral) {
        this.inicioLaboral = inicioLaboral;
    }




}


