package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Encargado generated by hbm2java
 */
@Entity
@Table(name="encargado"
    ,catalog="sigie"
)
public class Encargado  implements java.io.Serializable {


     private int dpiEncargado;
     private Estudiante estudiante;
     private String nombres;
     private String apellidos;
     private String residencia;
     private String nombreTrabajo;
     private String parentesco;
     private Set reglamentos = new HashSet(0);
     private Set telefonoEncargados = new HashSet(0);
     private Set fichaInscripcions = new HashSet(0);
     private Set convenioPagoses = new HashSet(0);

    public Encargado() {
    }

	
    public Encargado(int dpiEncargado, Estudiante estudiante, String nombres, String apellidos, String residencia, String parentesco) {
        this.dpiEncargado = dpiEncargado;
        this.estudiante = estudiante;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.residencia = residencia;
        this.parentesco = parentesco;
    }
    public Encargado(int dpiEncargado, Estudiante estudiante, String nombres, String apellidos, String residencia, String nombreTrabajo, String parentesco, Set reglamentos, Set telefonoEncargados, Set fichaInscripcions, Set convenioPagoses) {
       this.dpiEncargado = dpiEncargado;
       this.estudiante = estudiante;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.residencia = residencia;
       this.nombreTrabajo = nombreTrabajo;
       this.parentesco = parentesco;
       this.reglamentos = reglamentos;
       this.telefonoEncargados = telefonoEncargados;
       this.fichaInscripcions = fichaInscripcions;
       this.convenioPagoses = convenioPagoses;
    }
   
     @Id 

    
    @Column(name="Dpi_encargado", unique=true, nullable=false)
    public int getDpiEncargado() {
        return this.dpiEncargado;
    }
    
    public void setDpiEncargado(int dpiEncargado) {
        this.dpiEncargado = dpiEncargado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Estudiante_idEstudiante", nullable=false)
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    
    @Column(name="Nombres", nullable=false, length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="Apellidos", nullable=false, length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="Residencia", nullable=false, length=45)
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }

    
    @Column(name="Nombre_trabajo", length=45)
    public String getNombreTrabajo() {
        return this.nombreTrabajo;
    }
    
    public void setNombreTrabajo(String nombreTrabajo) {
        this.nombreTrabajo = nombreTrabajo;
    }

    
    @Column(name="Parentesco", nullable=false, length=10)
    public String getParentesco() {
        return this.parentesco;
    }
    
    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="encargado")
    public Set getReglamentos() {
        return this.reglamentos;
    }
    
    public void setReglamentos(Set reglamentos) {
        this.reglamentos = reglamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="encargado")
    public Set getTelefonoEncargados() {
        return this.telefonoEncargados;
    }
    
    public void setTelefonoEncargados(Set telefonoEncargados) {
        this.telefonoEncargados = telefonoEncargados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="encargado")
    public Set getFichaInscripcions() {
        return this.fichaInscripcions;
    }
    
    public void setFichaInscripcions(Set fichaInscripcions) {
        this.fichaInscripcions = fichaInscripcions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="encargado")
    public Set getConvenioPagoses() {
        return this.convenioPagoses;
    }
    
    public void setConvenioPagoses(Set convenioPagoses) {
        this.convenioPagoses = convenioPagoses;
    }




}


