package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
    ,catalog="sigie"
)
public class Personal  implements java.io.Serializable {


     private int dpiPersonal;
     private String nombre;
     private String apellidos;
     private String residencia;
     private Integer edad;
     private Date fechaNacimiento;
     private String estadoCivil;
     private Set datoProfesions = new HashSet(0);
     private Set telefonoPersonals = new HashSet(0);
     private Set infoDocentes = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set titulos = new HashSet(0);

    public Personal() {
    }

	
    public Personal(int dpiPersonal, String nombre, String apellidos, Date fechaNacimiento) {
        this.dpiPersonal = dpiPersonal;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Personal(int dpiPersonal, String nombre, String apellidos, String residencia, Integer edad, Date fechaNacimiento, String estadoCivil, Set datoProfesions, Set telefonoPersonals, Set infoDocentes, Set usuarios, Set titulos) {
       this.dpiPersonal = dpiPersonal;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.residencia = residencia;
       this.edad = edad;
       this.fechaNacimiento = fechaNacimiento;
       this.estadoCivil = estadoCivil;
       this.datoProfesions = datoProfesions;
       this.telefonoPersonals = telefonoPersonals;
       this.infoDocentes = infoDocentes;
       this.usuarios = usuarios;
       this.titulos = titulos;
    }
   
     @Id 

    
    @Column(name="DPI_personal", unique=true, nullable=false)
    public int getDpiPersonal() {
        return this.dpiPersonal;
    }
    
    public void setDpiPersonal(int dpiPersonal) {
        this.dpiPersonal = dpiPersonal;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellidos", nullable=false, length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="Residencia", length=45)
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }

    
    @Column(name="Edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_Nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="Estado_civil", length=45)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personal")
    public Set getDatoProfesions() {
        return this.datoProfesions;
    }
    
    public void setDatoProfesions(Set datoProfesions) {
        this.datoProfesions = datoProfesions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personal")
    public Set getTelefonoPersonals() {
        return this.telefonoPersonals;
    }
    
    public void setTelefonoPersonals(Set telefonoPersonals) {
        this.telefonoPersonals = telefonoPersonals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personal")
    public Set getInfoDocentes() {
        return this.infoDocentes;
    }
    
    public void setInfoDocentes(Set infoDocentes) {
        this.infoDocentes = infoDocentes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personal")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personal")
    public Set getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set titulos) {
        this.titulos = titulos;
    }




}


