package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String dpi;
     private String apellidos;
     private String nombre;
     private String residencia;
     private String edad;
     private Date fechaNacimiento;
     private String estadoCivil;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Encargado> encargados = new HashSet<Encargado>(0);
     private Set<Telefono> telefonos = new HashSet<Telefono>(0);

    public Persona() {
    }

	
    public Persona(String dpi, String apellidos, String nombre, String residencia, String edad, Date fechaNacimiento, String estadoCivil) {
        this.dpi = dpi;
        this.apellidos = apellidos;
        this.nombre = nombre;
        this.residencia = residencia;
        this.edad = edad;
        this.fechaNacimiento = fechaNacimiento;
        this.estadoCivil = estadoCivil;
    }
    public Persona(String dpi, String apellidos, String nombre, String residencia, String edad, Date fechaNacimiento, String estadoCivil, Set<Empleado> empleados, Set<Encargado> encargados, Set<Telefono> telefonos) {
       this.dpi = dpi;
       this.apellidos = apellidos;
       this.nombre = nombre;
       this.residencia = residencia;
       this.edad = edad;
       this.fechaNacimiento = fechaNacimiento;
       this.estadoCivil = estadoCivil;
       this.empleados = empleados;
       this.encargados = encargados;
       this.telefonos = telefonos;
    }
   
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
    public Set<Encargado> getEncargados() {
        return this.encargados;
    }
    
    public void setEncargados(Set<Encargado> encargados) {
        this.encargados = encargados;
    }
    public Set<Telefono> getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }




}


