package modelo;
// Generated 19/04/2016 01:02:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private String dpi;
     private String nombre;
     private String apellidos;
     private String residencia;
     private String edad;
     private Date fechaNacimiento;
     private String estadoCivil;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Telefono> telefonos = new HashSet<Telefono>(0);

    public Persona() {
    }

	
    public Persona(String dpi, String nombre, String apellidos, String residencia, Date fechaNacimiento, String estadoCivil) {
        this.dpi = dpi;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.residencia = residencia;
        this.fechaNacimiento = fechaNacimiento;
        this.estadoCivil = estadoCivil;
    }
    public Persona(String dpi, String nombre, String apellidos, String residencia, String edad, Date fechaNacimiento, String estadoCivil, Set<Usuario> usuarios, Set<Telefono> telefonos) {
       this.dpi = dpi;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.residencia = residencia;
       this.edad = edad;
       this.fechaNacimiento = fechaNacimiento;
       this.estadoCivil = estadoCivil;
       this.usuarios = usuarios;
       this.telefonos = telefonos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Telefono> getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }




}


