package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Promedio generated by hbm2java
 */
public class Promedio  implements java.io.Serializable {


     private Integer idpromedio;
     private String promedio;
     private Set<Notas> notases = new HashSet<Notas>(0);
     private Set<Historial> historials = new HashSet<Historial>(0);

    public Promedio() {
    }

	
    public Promedio(String promedio) {
        this.promedio = promedio;
    }
    public Promedio(String promedio, Set<Notas> notases, Set<Historial> historials) {
       this.promedio = promedio;
       this.notases = notases;
       this.historials = historials;
    }
   
    public Integer getIdpromedio() {
        return this.idpromedio;
    }
    
    public void setIdpromedio(Integer idpromedio) {
        this.idpromedio = idpromedio;
    }
    public String getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(String promedio) {
        this.promedio = promedio;
    }
    public Set<Notas> getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set<Notas> notases) {
        this.notases = notases;
    }
    public Set<Historial> getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set<Historial> historials) {
        this.historials = historials;
    }




}


