package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reglamento generated by hbm2java
 */
@Entity
@Table(name="reglamento"
    ,catalog="sigie"
)
public class Reglamento  implements java.io.Serializable {


     private int idReglamento;
     private Encargado encargado;
     private Estudiante estudiante;
     private Date fechaReglamento;

    public Reglamento() {
    }

    public Reglamento(int idReglamento, Encargado encargado, Estudiante estudiante, Date fechaReglamento) {
       this.idReglamento = idReglamento;
       this.encargado = encargado;
       this.estudiante = estudiante;
       this.fechaReglamento = fechaReglamento;
    }
   
     @Id 

    
    @Column(name="idReglamento", unique=true, nullable=false)
    public int getIdReglamento() {
        return this.idReglamento;
    }
    
    public void setIdReglamento(int idReglamento) {
        this.idReglamento = idReglamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Encargado_Dpi_encargado", nullable=false)
    public Encargado getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(Encargado encargado) {
        this.encargado = encargado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Estudiante_idEstudiante", nullable=false)
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_reglamento", nullable=false, length=10)
    public Date getFechaReglamento() {
        return this.fechaReglamento;
    }
    
    public void setFechaReglamento(Date fechaReglamento) {
        this.fechaReglamento = fechaReglamento;
    }




}


