package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TelefonoPersonal generated by hbm2java
 */
@Entity
@Table(name="telefono_personal"
    ,catalog="sigie"
)
public class TelefonoPersonal  implements java.io.Serializable {


     private int numero;
     private Personal personal;
     private String identificador;

    public TelefonoPersonal() {
    }

    public TelefonoPersonal(int numero, Personal personal, String identificador) {
       this.numero = numero;
       this.personal = personal;
       this.identificador = identificador;
    }
   
     @Id 

    
    @Column(name="Numero", unique=true, nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Personal_DPI", nullable=false)
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }

    
    @Column(name="Identificador", nullable=false, length=10)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }




}


