package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Titulo generated by hbm2java
 */
public class Titulo  implements java.io.Serializable {


     private int registroTitulo;
     private Date anioGraduacion;
     private String profesion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Titulo() {
    }

	
    public Titulo(int registroTitulo, Date anioGraduacion, String profesion) {
        this.registroTitulo = registroTitulo;
        this.anioGraduacion = anioGraduacion;
        this.profesion = profesion;
    }
    public Titulo(int registroTitulo, Date anioGraduacion, String profesion, Set<Empleado> empleados) {
       this.registroTitulo = registroTitulo;
       this.anioGraduacion = anioGraduacion;
       this.profesion = profesion;
       this.empleados = empleados;
    }
   
    public int getRegistroTitulo() {
        return this.registroTitulo;
    }
    
    public void setRegistroTitulo(int registroTitulo) {
        this.registroTitulo = registroTitulo;
    }
    public Date getAnioGraduacion() {
        return this.anioGraduacion;
    }
    
    public void setAnioGraduacion(Date anioGraduacion) {
        this.anioGraduacion = anioGraduacion;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


