package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Titulo generated by hbm2java
 */
@Entity
@Table(name="titulo"
    ,catalog="sigie"
)
public class Titulo  implements java.io.Serializable {


     private TituloId id;
     private Personal personal;
     private Date anioGraduacion;
     private String profesion;

    public Titulo() {
    }

	
    public Titulo(TituloId id, Personal personal, String profesion) {
        this.id = id;
        this.personal = personal;
        this.profesion = profesion;
    }
    public Titulo(TituloId id, Personal personal, Date aniooGraduacion, String profesion) {
       this.id = id;
       this.personal = personal;
       this.anioGraduacion = anioGraduacion;
       this.profesion = profesion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="registroTitulo", column=@Column(name="Registro_titulo", nullable=false) ), 
        @AttributeOverride(name="personalDpiPersonal", column=@Column(name="Personal_DPI_personal", nullable=false) ) } )
    public TituloId getId() {
        return this.id;
    }
    
    public void setId(TituloId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Personal_DPI_personal", nullable=false, insertable=false, updatable=false)
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Año_graduacion", length=10)
    public Date getAnioGraduacion() {
        return this.anioGraduacion;
    }
    
    public void setAnioGraduacion(Date anioGraduacion) {
        this.anioGraduacion = anioGraduacion;
    }

    
    @Column(name="Profesion", nullable=false, length=100)
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }




}


