package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Encargado generated by hbm2java
 */
public class Encargado  implements java.io.Serializable {


     private Integer idencargado;
     private Persona persona;
     private String nombreTrabajo;
     private String parentesco;
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Encargado() {
    }

	
    public Encargado(Persona persona, String nombreTrabajo, String parentesco) {
        this.persona = persona;
        this.nombreTrabajo = nombreTrabajo;
        this.parentesco = parentesco;
    }
    public Encargado(Persona persona, String nombreTrabajo, String parentesco, Set<Estudiante> estudiantes) {
       this.persona = persona;
       this.nombreTrabajo = nombreTrabajo;
       this.parentesco = parentesco;
       this.estudiantes = estudiantes;
    }
   
    public Integer getIdencargado() {
        return this.idencargado;
    }
    
    public void setIdencargado(Integer idencargado) {
        this.idencargado = idencargado;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombreTrabajo() {
        return this.nombreTrabajo;
    }
    
    public void setNombreTrabajo(String nombreTrabajo) {
        this.nombreTrabajo = nombreTrabajo;
    }
    public String getParentesco() {
        return this.parentesco;
    }
    
    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


