package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name="estudiante"
    ,catalog="sigie"
)
public class Estudiante  implements java.io.Serializable {


     private int idEstudiante;
     private String nombre;
     private String apellido;
     private Date fechaDeNacimiento;
     private int cui;
     private String lugarDeNaciomiento;
     private Integer edad;
     private Set encargados = new HashSet(0);
     private Set notases = new HashSet(0);
     private Set fichaInscripcions = new HashSet(0);
     private Set reglamentos = new HashSet(0);
     private Set convenioPagoses = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(int idEstudiante, String nombre, String apellido, Date fechaDeNacimiento, int cui, String lugarDeNaciomiento) {
        this.idEstudiante = idEstudiante;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaDeNacimiento = fechaDeNacimiento;
        this.cui = cui;
        this.lugarDeNaciomiento = lugarDeNaciomiento;
    }
    public Estudiante(int idEstudiante, String nombre, String apellido, Date fechaDeNacimiento, int cui, String lugarDeNaciomiento, Integer edad, Set encargados, Set notases, Set fichaInscripcions, Set reglamentos, Set convenioPagoses) {
       this.idEstudiante = idEstudiante;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.cui = cui;
       this.lugarDeNaciomiento = lugarDeNaciomiento;
       this.edad = edad;
       this.encargados = encargados;
       this.notases = notases;
       this.fichaInscripcions = fichaInscripcions;
       this.reglamentos = reglamentos;
       this.convenioPagoses = convenioPagoses;
    }
   
     @Id 

    
    @Column(name="idEstudiante", unique=true, nullable=false)
    public int getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(int idEstudiante) {
        this.idEstudiante = idEstudiante;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", nullable=false, length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_de_nacimiento", nullable=false, length=10)
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    
    public void setFechaDeNacimiento(Date fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }

    
    @Column(name="cui", nullable=false)
    public int getCui() {
        return this.cui;
    }
    
    public void setCui(int cui) {
        this.cui = cui;
    }

    
    @Column(name="Lugar_de_Naciomiento", nullable=false, length=45)
    public String getLugarDeNaciomiento() {
        return this.lugarDeNaciomiento;
    }
    
    public void setLugarDeNaciomiento(String lugarDeNaciomiento) {
        this.lugarDeNaciomiento = lugarDeNaciomiento;
    }

    
    @Column(name="edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set getEncargados() {
        return this.encargados;
    }
    
    public void setEncargados(Set encargados) {
        this.encargados = encargados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set getFichaInscripcions() {
        return this.fichaInscripcions;
    }
    
    public void setFichaInscripcions(Set fichaInscripcions) {
        this.fichaInscripcions = fichaInscripcions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set getReglamentos() {
        return this.reglamentos;
    }
    
    public void setReglamentos(Set reglamentos) {
        this.reglamentos = reglamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estudiante")
    public Set getConvenioPagoses() {
        return this.convenioPagoses;
    }
    
    public void setConvenioPagoses(Set convenioPagoses) {
        this.convenioPagoses = convenioPagoses;
    }




}


