package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FichaInscripcion generated by hbm2java
 */
@Entity
@Table(name="ficha_inscripcion"
    ,catalog="sigie"
)
public class FichaInscripcion  implements java.io.Serializable {


     private int idFichaInscripcion;
     private Encargado encargado;
     private Estudiante estudiante;
     private Date fechaInscripcion;
     private String observaciones;

    public FichaInscripcion() {
    }

	
    public FichaInscripcion(int idFichaInscripcion, Encargado encargado, Estudiante estudiante, Date fechaInscripcion) {
        this.idFichaInscripcion = idFichaInscripcion;
        this.encargado = encargado;
        this.estudiante = estudiante;
        this.fechaInscripcion = fechaInscripcion;
    }
    public FichaInscripcion(int idFichaInscripcion, Encargado encargado, Estudiante estudiante, Date fechaInscripcion, String observaciones) {
       this.idFichaInscripcion = idFichaInscripcion;
       this.encargado = encargado;
       this.estudiante = estudiante;
       this.fechaInscripcion = fechaInscripcion;
       this.observaciones = observaciones;
    }
   
     @Id 

    
    @Column(name="idFicha_inscripcion", unique=true, nullable=false)
    public int getIdFichaInscripcion() {
        return this.idFichaInscripcion;
    }
    
    public void setIdFichaInscripcion(int idFichaInscripcion) {
        this.idFichaInscripcion = idFichaInscripcion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Encargado_Dpi_encargado", nullable=false)
    public Encargado getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(Encargado encargado) {
        this.encargado = encargado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Estudiante_idEstudiante", nullable=false)
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha_inscripcion", nullable=false, length=10)
    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }
    
    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }

    
    @Column(name="observaciones", length=100)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


