package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private Integer idgrado;
     private AreaCurricular areaCurricular;
     private Seccion seccion;
     private String nombreGrado;
     private Set<CicloHasGrado> cicloHasGrados = new HashSet<CicloHasGrado>(0);
     private Set<Historial> historials = new HashSet<Historial>(0);

    public Grado() {
    }

	
    public Grado(AreaCurricular areaCurricular, Seccion seccion, String nombreGrado) {
        this.areaCurricular = areaCurricular;
        this.seccion = seccion;
        this.nombreGrado = nombreGrado;
    }
    public Grado(AreaCurricular areaCurricular, Seccion seccion, String nombreGrado, Set<CicloHasGrado> cicloHasGrados, Set<Historial> historials) {
       this.areaCurricular = areaCurricular;
       this.seccion = seccion;
       this.nombreGrado = nombreGrado;
       this.cicloHasGrados = cicloHasGrados;
       this.historials = historials;
    }
   
    public Integer getIdgrado() {
        return this.idgrado;
    }
    
    public void setIdgrado(Integer idgrado) {
        this.idgrado = idgrado;
    }
    public AreaCurricular getAreaCurricular() {
        return this.areaCurricular;
    }
    
    public void setAreaCurricular(AreaCurricular areaCurricular) {
        this.areaCurricular = areaCurricular;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public String getNombreGrado() {
        return this.nombreGrado;
    }
    
    public void setNombreGrado(String nombreGrado) {
        this.nombreGrado = nombreGrado;
    }
    public Set<CicloHasGrado> getCicloHasGrados() {
        return this.cicloHasGrados;
    }
    
    public void setCicloHasGrados(Set<CicloHasGrado> cicloHasGrados) {
        this.cicloHasGrados = cicloHasGrados;
    }
    public Set<Historial> getHistorials() {
        return this.historials;
    }
    
    public void setHistorials(Set<Historial> historials) {
        this.historials = historials;
    }




}


