package modelo;
// Generated 18/04/2016 12:26:36 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InfoDocente generated by hbm2java
 */
public class InfoDocente  implements java.io.Serializable {


     private String cedulaDocente;
     private Empleado empleado;
     private Date fechaEmision;
     private String claseEscalafonaria;
     private Date fechaAscenso;

    public InfoDocente() {
    }

	
    public InfoDocente(String cedulaDocente, Empleado empleado) {
        this.cedulaDocente = cedulaDocente;
        this.empleado = empleado;
    }
    public InfoDocente(String cedulaDocente, Empleado empleado, Date fechaEmision, String claseEscalafonaria, Date fechaAscenso) {
       this.cedulaDocente = cedulaDocente;
       this.empleado = empleado;
       this.fechaEmision = fechaEmision;
       this.claseEscalafonaria = claseEscalafonaria;
       this.fechaAscenso = fechaAscenso;
    }
   
    public String getCedulaDocente() {
        return this.cedulaDocente;
    }
    
    public void setCedulaDocente(String cedulaDocente) {
        this.cedulaDocente = cedulaDocente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public String getClaseEscalafonaria() {
        return this.claseEscalafonaria;
    }
    
    public void setClaseEscalafonaria(String claseEscalafonaria) {
        this.claseEscalafonaria = claseEscalafonaria;
    }
    public Date getFechaAscenso() {
        return this.fechaAscenso;
    }
    
    public void setFechaAscenso(Date fechaAscenso) {
        this.fechaAscenso = fechaAscenso;
    }




}


