package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notas generated by hbm2java
 */
@Entity
@Table(name="notas"
    ,catalog="sigie"
)
public class Notas  implements java.io.Serializable {


     private int idhistorial;
     private AreaCurricular areaCurricular;
     private Estudiante estudiante;
     private Grado grado;
     private int ciclo;
     private char seccion;
     private Integer bim1;
     private Integer bim2;
     private Integer bim3;
     private Integer bim4;

    public Notas() {
    }

	
    public Notas(int idhistorial, AreaCurricular areaCurricular, Estudiante estudiante, Grado grado, int ciclo, char seccion) {
        this.idhistorial = idhistorial;
        this.areaCurricular = areaCurricular;
        this.estudiante = estudiante;
        this.grado = grado;
        this.ciclo = ciclo;
        this.seccion = seccion;
    }
    public Notas(int idhistorial, AreaCurricular areaCurricular, Estudiante estudiante, Grado grado, int ciclo, char seccion, Integer bim1, Integer bim2, Integer bim3, Integer bim4) {
       this.idhistorial = idhistorial;
       this.areaCurricular = areaCurricular;
       this.estudiante = estudiante;
       this.grado = grado;
       this.ciclo = ciclo;
       this.seccion = seccion;
       this.bim1 = bim1;
       this.bim2 = bim2;
       this.bim3 = bim3;
       this.bim4 = bim4;
    }
   
     @Id 

    
    @Column(name="idhistorial", unique=true, nullable=false)
    public int getIdhistorial() {
        return this.idhistorial;
    }
    
    public void setIdhistorial(int idhistorial) {
        this.idhistorial = idhistorial;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Area_curricular_idArea_curricular", nullable=false)
    public AreaCurricular getAreaCurricular() {
        return this.areaCurricular;
    }
    
    public void setAreaCurricular(AreaCurricular areaCurricular) {
        this.areaCurricular = areaCurricular;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Estudiante_idEstudiante", nullable=false)
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grado_idgrado", nullable=false)
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }

    
    @Column(name="ciclo", nullable=false)
    public int getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(int ciclo) {
        this.ciclo = ciclo;
    }

    
    @Column(name="seccion", nullable=false, length=1)
    public char getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(char seccion) {
        this.seccion = seccion;
    }

    
    @Column(name="bim1")
    public Integer getBim1() {
        return this.bim1;
    }
    
    public void setBim1(Integer bim1) {
        this.bim1 = bim1;
    }

    
    @Column(name="bim2")
    public Integer getBim2() {
        return this.bim2;
    }
    
    public void setBim2(Integer bim2) {
        this.bim2 = bim2;
    }

    
    @Column(name="bim3")
    public Integer getBim3() {
        return this.bim3;
    }
    
    public void setBim3(Integer bim3) {
        this.bim3 = bim3;
    }

    
    @Column(name="bim4")
    public Integer getBim4() {
        return this.bim4;
    }
    
    public void setBim4(Integer bim4) {
        this.bim4 = bim4;
    }




}


