package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TelefonoEncargado generated by hbm2java
 */
@Entity
@Table(name="telefono_encargado"
    ,catalog="sigie"
)
public class TelefonoEncargado  implements java.io.Serializable {


     private int telefono;
     private Encargado encargado;
     private String identificador;

    public TelefonoEncargado() {
    }

    public TelefonoEncargado(int telefono, Encargado encargado, String identificador) {
       this.telefono = telefono;
       this.encargado = encargado;
       this.identificador = identificador;
    }
   
     @Id 

    
    @Column(name="Telefono", unique=true, nullable=false)
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Encargado_Dpi_encargado", nullable=false)
    public Encargado getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(Encargado encargado) {
        this.encargado = encargado;
    }

    
    @Column(name="Identificador", nullable=false, length=10)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }




}


