package modelo;
// Generated 3/04/2016 12:08:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TituloId generated by hbm2java
 */
@Embeddable
public class TituloId  implements java.io.Serializable {


     private int registroTitulo;
     private int personalDpiPersonal;

    public TituloId() {
    }

    public TituloId(int registroTitulo, int personalDpiPersonal) {
       this.registroTitulo = registroTitulo;
       this.personalDpiPersonal = personalDpiPersonal;
    }
   


    @Column(name="Registro_titulo", nullable=false)
    public int getRegistroTitulo() {
        return this.registroTitulo;
    }
    
    public void setRegistroTitulo(int registroTitulo) {
        this.registroTitulo = registroTitulo;
    }


    @Column(name="Personal_DPI_personal", nullable=false)
    public int getPersonalDpiPersonal() {
        return this.personalDpiPersonal;
    }
    
    public void setPersonalDpiPersonal(int personalDpiPersonal) {
        this.personalDpiPersonal = personalDpiPersonal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TituloId) ) return false;
		 TituloId castOther = ( TituloId ) other; 
         
		 return (this.getRegistroTitulo()==castOther.getRegistroTitulo())
 && (this.getPersonalDpiPersonal()==castOther.getPersonalDpiPersonal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRegistroTitulo();
         result = 37 * result + this.getPersonalDpiPersonal();
         return result;
   }   


}


